### ISSUE TITLE
代码结构重新构造

### ISSUE THREAD

**Issue by Keithnier** [Keithnier/ADE_DataGetter#2]
### 为什么要做这个工作？
> 爬虫部分和IR-Tree部分混在一起了，看名字不知道具体功能是什么
> 重新组织一下代码，便于阅读，同时便于按模块修改代码

### 完成标准是什么？
1. 根目录下仅有原来的爬虫部分DataCrawler，DataPreprocess，IRtree三个包  
``` shell
.src
├── DataCrawler
├── DataPreprocess
└── IRTree
```
2. 程序可以运行至**---App Start---**

### 有什么要求
没啥，任务完成记得提交代码，完成issue

### 具体步骤
我是这么想的
按文件夹的形式来吧
先把文件夹建好，把代码移过去，再改每个**.java**文件前面的**package**名字

### 其他
@ljscoding 交给你了

**Comment by ljscoding** [comment]
OK
